"""init

Revision ID: 82739f8afe93
Revises: 
Create Date: 2025-12-11 18:17:51.493716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import advanced_alchemy

# revision identifiers, used by Alembic.
revision: str = '82739f8afe93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.alter_column('book', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('book', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('book', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('book', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('order', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('reader', sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True))
    op.alter_column('reader', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reader', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reader', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reader', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('reader', 'sa_orm_sentinel')
    op.alter_column('order', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('order', 'sa_orm_sentinel')
    op.alter_column('book', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('book', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('book', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('book', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('book', 'sa_orm_sentinel')
    op.drop_column('author', 'sa_orm_sentinel')
    # ### end Alembic commands ###
